# Starter pipeline
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Demo-Conn'
    subscriptionId: '903c571d-b081-4db2-a4bf-9e0821145b83'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG_RaviTest'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/kistipatiravireddy/myarmtemplates/master/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/kistipatiravireddy/myarmtemplates/master/azuredeploy.parameters.json'
    deploymentMode: 'Validation'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Sample-Con'
    subscriptionId: '903c571d-b081-4db2-a4bf-9e0821145b83'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG_RaviTest'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/kistipatiravireddy/myarmtemplates/master/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/kistipatiravireddy/myarmtemplates/master/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
